// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igthrohphycxtjyipflr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndGhyb2hwaHljeHRqeWlwZmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzE5ODQsImV4cCI6MjA1ODY0Nzk4NH0.Fm6i6oiRu5l7e1pZTxHlj2fjfADjIFLc-VgfwEDd8Cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);